import Link from "next/link";
import { Hero } from "@/components/hero";
import { IconArrowUpRight, IconMapPin, IconPhone } from "@tabler/icons-react";
import { publicContent } from "@/lib/store";
import { BUSINESS } from "@/lib/types";
import { Contact } from "@/components/contact";
import { WorkGrid } from "@/components/work-grid";
export const dynamic = "force-dynamic";
export default async function Home({ searchParams }: { searchParams: Promise<{ service?: string; vehicle?: string }> }) {
 const [{ services,work },query] = await Promise.all([publicContent(),searchParams]); const showroomIds = new Set(services.filter(s => s.type === "showroom").map(s => s.id)); const repairWork = work.filter(w => !showroomIds.has(w.serviceId)); const vehicle = work.find(w => showroomIds.has(w.serviceId));
 return <><Hero/><div className="location-strip"><div className="container"><span><IconMapPin size={18}/>220 Jackson St, Suffolk, VA</span><span>YOUR LOCAL PAINT, BODY & REPAIR SHOP</span><a href={`tel:${BUSINESS.tel}`}><IconPhone size={17}/>{BUSINESS.phone}</a></div></div><section className="section services-section"><div className="container"><div className="section-heading"><h2>WHATEVER THE ROAD<br/>THROWS AT YOU.</h2><p>One local shop. A range of ways to help your vehicle.</p></div><div className="service-list">{services.map((service,index) => { const photo = service.coverImage || work.find(w => w.serviceId === service.id)?.images[0]; return <Link className="service-tile" key={service.id} href={`/services/${service.slug}`}><span className="service-number">{String(index+1).padStart(2,"0")}</span>{photo && <img src={photo} alt="" loading="lazy" width="210" height="150"/>}<div><h3>{service.title}</h3><p>{service.description.split(".")[0]}.</p></div><IconArrowUpRight size={25}/></Link>; })}</div>{services.length === 0 && <p>Call us to discuss your vehicle and the services available.</p>}</div></section><section className="section work-section"><div className="container"><div className="section-heading"><h2>CUSTOMER CARS.<br/><span>THEIR STORIES.</span></h2><p>Each project is one customer’s vehicle, with its own photos and repair story.</p></div><div className="customer-projects"><WorkGrid items={repairWork.slice(0,3)} services={services}/></div><Link href="/services" className="text-link">Explore services<IconArrowUpRight size={18}/></Link></div></section>{vehicle && <section className="showroom-feature container"><div className="showroom-feature-photo"><img src={vehicle.images[0]} alt={vehicle.title} width="1000" height="650" loading="lazy"/></div><div className="showroom-feature-copy"><h2>YOUR NEXT<br/><span>SET OF KEYS.</span></h2><p>Take a look around our virtual showroom. Find something you like? Let’s talk.</p><Link className="button secondary" href="/showroom">Browse showroom<IconArrowUpRight size={18}/></Link><p className="demo-label">Demo vehicles shown for illustration.</p></div></section>}<Contact services={services} selectedService={services.some(s => s.id === query.service) ? query.service : undefined} vehicle={query.vehicle?.slice(0,120)}/></>;
}
