import Link from "next/link";
import Image from "next/image";
import { IconArrowUpRight, IconArrowRight, IconMapPin, IconPhone } from "@tabler/icons-react";
import { publicContent } from "@/lib/store";
import { BUSINESS } from "@/lib/types";
import { Contact } from "@/components/contact";
import { WorkGrid } from "@/components/work-grid";
export const dynamic = "force-dynamic";
export default async function Home({ searchParams }: { searchParams: Promise<{ service?: string; vehicle?: string }> }) {
 const [{ services,work },query] = await Promise.all([publicContent(),searchParams]); const showroomIds = new Set(services.filter(s => s.type === "showroom").map(s => s.id)); const repairWork = work.filter(w => !showroomIds.has(w.serviceId)); const vehicle = work.find(w => showroomIds.has(w.serviceId));
 return <><section className="hero"><Image className="hero-photo" src="/images/autobody-1.webp" alt="Illustrative restored red sports coupe in an automotive workshop" fill priority sizes="100vw"/><div className="hero-shade"/><div className="container hero-content"><p className="eyebrow">SUFFOLK, VIRGINIA</p><h1>MAKE IT<br/><span>NEW AGAIN.</span></h1><p>Bodywork, paint, and repairs.<br/>Local care for whatever you drive.</p><div className="hero-actions"><a href="#contact" className="button primary">Request a callback<IconArrowUpRight size={20}/></a><Link href="/services" className="hero-service-link">Explore services<IconArrowRight size={19}/></Link></div></div><div className="hero-caption">Illustrative demo photography</div></section><div className="location-strip"><div className="container"><span><IconMapPin size={18}/>220 Jackson St, Suffolk, VA</span><span>YOUR LOCAL PAINT, BODY & REPAIR SHOP</span><a href={`tel:${BUSINESS.tel}`}><IconPhone size={17}/>{BUSINESS.phone}</a></div></div><section className="section services-section"><div className="container"><div className="section-heading"><h2>WHATEVER THE ROAD<br/>THROWS AT YOU.</h2><p>One local shop. A range of ways to help your vehicle.</p></div><div className="service-list">{services.map((service,index) => { const photo = work.find(w => w.serviceId === service.id)?.images[0]; return <Link className="service-tile" key={service.id} href={`/services/${service.slug}`}><span className="service-number">{String(index+1).padStart(2,"0")}</span>{photo && <img src={photo} alt="" loading="lazy" width="210" height="150"/>}<div><h3>{service.title}</h3><p>{service.description.split(".")[0]}.</p></div><IconArrowUpRight size={25}/></Link>; })}</div>{services.length === 0 && <p>Call us to discuss your vehicle and the services available.</p>}</div></section><section className="section work-section"><div className="container"><div className="section-heading"><h2>IT’S ALL IN<br/><span>THE DETAILS.</span></h2><p>A glimpse at what the service galleries can showcase.</p></div><WorkGrid items={repairWork.slice(0,2)} services={services}/><Link href="/services" className="text-link">Explore services<IconArrowUpRight size={18}/></Link></div></section>{vehicle && <section className="showroom-feature container"><div className="showroom-feature-photo"><img src={vehicle.images[0]} alt={vehicle.title} width="1000" height="650" loading="lazy"/></div><div className="showroom-feature-copy"><h2>YOUR NEXT<br/><span>SET OF KEYS.</span></h2><p>Take a look around our virtual showroom. Find something you like? Let’s talk.</p><Link className="button secondary" href="/showroom">Browse showroom<IconArrowUpRight size={18}/></Link><p className="demo-label">Demo vehicles shown for illustration.</p></div></section>}<Contact services={services} selectedService={services.some(s => s.id === query.service) ? query.service : undefined} vehicle={query.vehicle?.slice(0,120)}/></>;
}
