"use client";
import { useState } from "react";
import { IconArrowUpRight, IconPhone, IconMapPin, IconCheck } from "@tabler/icons-react";
import { BUSINESS, type Service } from "@/lib/types";
export function Contact({ services, selectedService, vehicle }: { services: Service[]; selectedService?: string; vehicle?: string }) {
 const [error,setError] = useState(""); const [busy,setBusy] = useState(false); const [sent,setSent] = useState(false);
 async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setBusy(true); const form = new FormData(event.currentTarget); try { const response = await fetch("/api/inquiries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to send. Please try again."); setSent(true); } catch (error) { setError(error instanceof Error ? error.message : "Unable to send. Please call the shop."); } finally { setBusy(false); } }
 return <section id="contact" className="contact-section section"><div className="container contact-grid"><div className="contact-copy"><h2>LET’S GET YOU<br/><span>BACK ON THE ROAD.</span></h2><p>Tell us a little about your vehicle and what you need. The shop can follow up with you directly.</p><a className="contact-phone" href={`tel:${BUSINESS.tel}`}><IconPhone size={26}/>{BUSINESS.phone}<IconArrowUpRight size={22}/></a><a className="address-link" href={BUSINESS.directions} target="_blank" rel="noreferrer"><IconMapPin size={20}/><span>220 Jackson St<br/>Suffolk, VA 23434</span><IconArrowUpRight size={18}/></a><p className="contact-note">Prefer to talk it through? Give us a call.</p></div><div className="contact-form-wrap">{sent ? <div className="success-panel" role="status"><IconCheck size={42}/><h3>Message received.</h3><p>Your inquiry is saved. If you need to speak with someone now, call {BUSINESS.phone}.</p><button className="button secondary" onClick={() => setSent(false)}>Send another inquiry</button></div> : <form onSubmit={submit} className="contact-form"><h3>Request a callback</h3><div className="form-row"><label>Your name<input name="name" autoComplete="name" required maxLength={100} placeholder="First and last name"/></label><label>Phone number<input name="phone" type="tel" autoComplete="tel" required minLength={7} maxLength={30} placeholder="(757) 555-0123"/></label></div><label>Email <span className="optional">(optional)</span><input name="email" type="email" autoComplete="email" maxLength={254} placeholder="you@example.com"/></label><label>How can we help?<select name="serviceId" defaultValue={selectedService || ""} required><option value="" disabled>Select a service</option>{services.map(service => <option key={service.id} value={service.id}>{service.title}</option>)}</select></label><label>Tell us about your vehicle<textarea name="message" rows={4} required maxLength={2000} defaultValue={vehicle ? `I'm interested in ${vehicle}. Please contact me with more information.` : ""} placeholder="Vehicle year, make, model, and what you need help with..."/></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="button primary" disabled={busy || services.length === 0}>{busy ? "Saving inquiry..." : "Request a callback"}<IconArrowUpRight size={18}/></button><p className="form-helper">Your contact details are used to respond to your inquiry. Demo submissions are saved only; no email is sent.</p></form>}</div></div></section>;
}
