"use client";
import { useRef, useState } from "react";
import { IconArrowUpRight, IconX, IconChevronLeft, IconChevronRight } from "@tabler/icons-react";
import type { Work, Service } from "@/lib/types";
export const money = (value?: number) => value === undefined ? "Ask for price" : new Intl.NumberFormat("en-US", { style:"currency", currency:"USD", maximumFractionDigits:0 }).format(value);
export function WorkGrid({ items, services, showroom = false }: { items: Work[]; services: Service[]; showroom?: boolean }) {
 const dialog = useRef<HTMLDialogElement>(null); const [selected,setSelected] = useState<Work | null>(null); const [index,setIndex] = useState(0);
 function open(item: Work) { setSelected(item); setIndex(0); dialog.current?.showModal(); }
 function close() { dialog.current?.close(); setSelected(null); }
 return <><div className={showroom ? "work-grid vehicle-grid" : "work-grid"}>{items.map(item => <article key={item.id} className="work-card"><button className="image-button" onClick={() => open(item)} aria-label={`View ${item.title}`}><img src={item.images[0]} alt={item.title} loading="lazy" width="900" height="600"/><span className="image-arrow"><IconArrowUpRight size={23}/></span></button><div className="work-card-info">{showroom && <p className="vehicle-meta">{item.availability === "sold" ? "Sold" : "Available"}{item.mileage !== undefined ? ` / ${item.mileage.toLocaleString("en-US")} miles` : ""}</p>}<h3><button onClick={() => open(item)}>{item.title}</button></h3>{showroom ? <p className="vehicle-price">{money(item.price)}</p> : <p>{services.find(s => s.id === item.serviceId)?.title}</p>}{item.demo && <p className="demo-label">{showroom ? "Demo listing, not actual inventory" : "Illustrative demo photo"}</p>}</div></article>)}</div>{items.length === 0 && <div className="empty-state"><h3>{showroom ? "More vehicles coming soon." : "More work coming soon."}</h3><p>Contact the shop to discuss {showroom ? "current availability" : "your vehicle"}.</p></div>}<dialog ref={dialog} className="gallery-dialog" onCancel={() => setSelected(null)} onClick={event => { if (event.target === event.currentTarget) close(); }}>{selected && <div className="gallery-dialog-content"><button className="dialog-close" onClick={close} aria-label="Close photo gallery"><IconX/></button><div className="gallery-image"><img src={selected.images[index]} alt={`${selected.title}, photo ${index+1}`}/>{selected.images.length > 1 && <><button className="gallery-prev" aria-label="Previous photo" onClick={() => setIndex((index - 1 + selected.images.length) % selected.images.length)}><IconChevronLeft/></button><button className="gallery-next" aria-label="Next photo" onClick={() => setIndex((index+1) % selected.images.length)}><IconChevronRight/></button><p className="image-count" aria-live="polite">{index+1} / {selected.images.length}</p></>}</div><div className="gallery-description"><h2>{selected.title}</h2><p>{selected.description}</p>{showroom && <p className="vehicle-price">{money(selected.price)}{selected.mileage !== undefined && <span> / {selected.mileage.toLocaleString("en-US")} miles</span>}</p>}{selected.demo && <p className="demo-label">Illustrative demo content. {showroom ? "This vehicle is not actual inventory." : "This is not a photo of the shop’s actual work."}</p>}<a className="button primary" href={`/?service=${encodeURIComponent(selected.serviceId)}${showroom ? `&vehicle=${encodeURIComponent(selected.title)}` : ""}#contact`}>Request a callback<IconArrowUpRight size={18}/></a></div></div>}</dialog></>;
}
